fos_user:
  use_flash_notifications: false
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "spam@gmail.com" #TODO: fix me
    sender_name: "spam" #TODO: fix me
  registration:
    confirmation:
      enabled: true
    form:
      type: App\Form\RegistrationType